export enum NavigationItem {
  Login = 'Login',
  AppOptions = 'AppOptions',
  Tabs = 'Tabs',
  Dashboard = 'Dashboard',
  DashboardStack = 'DashboardStack',
  Reporting = 'Reporting',
  More = 'More',
  BarcodeScanner = 'BarcodeScanner',
  ScanFail = 'ScanFail',
  ManualScan = 'ManualScan',
  ItemDetails = 'ItemDetails',
  PriceSync = 'PriceSync',
  PriceVerify = 'PriceVerify',
  CountDocumentList = 'CountDocumentList',
  ChooseCountType = 'ChooseCountType',
  NameYourDocument = 'NameYourDocument',
  FreeCountList = 'FreeCountList',
  PriceOverride = 'PriceOverride',
  EditItem = 'EditItem',
  AddNewItem = 'AddNewItem',
  InventoryItemDetails = 'InventoryItemDetails',
  InventoryItemList = 'InventoryItemList',
  ShelfTag = 'ShelfTag',
  ItemAdded = 'ItemAdded',
  CountSummary = 'CountSummary',
  EditItemShelfTag = 'EditItemShelfTag',
  InventoryAdjustmentsList = 'InventoryAdjustmentsList',
  AdjustmentItemDetails = 'AdjustmentItemDetails',
}

export enum Modules {
  ReleaseToPOS = 'ReleaseToPOS',
  PriceVerification = 'PriceVerification',
  CountDocumentList = 'CountDocumentList',
  FreeCountList = 'FreeCountList',
  EditItem = 'EditItem',
  NewItem = 'NewItem',
}
