export const USER_LOGOUT = 'USER_LOGOUT'

export const LAUNCH_DARKLY_SUCCESS = 'LAUNCH_DARKLY_SUCCESS'
export const LAUNCH_DARKLY_ERROR = 'LAUNCH_DARKLY_ERROR'

export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const ITEM_DETAILS_START = 'ITEM_DETAILS_START'
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_ERROR = 'ITEM_DETAILS_ERROR'
export const ITEM_PRICE_RELEASED_TO_POS = 'ITEM_PRICE_RELEASED_TO_POS'
export const CLEAR_ITEM_PRICE_RELEASED_TO_POS = 'CLEAR_ITEM_PRICE_RELEASED_TO_POS'

export const PRICE_SYNC_START = 'PRICE_SYNC_START'
export const PRICE_SYNC_SUCCESS = 'PRICE_SYNC_SUCCESS'
export const PRICE_SYNC_ERROR = 'PRICE_SYNC_ERROR'

export const PRICE_VERIFY_START = 'PRICE_VERIFY_START'
export const PRICE_VERIFY_SUCCESS = 'PRICE_VERIFY_SUCCESS'
export const PRICE_VERIFY_ERROR = 'PRICE_VERIFY_ERROR'

export const SAVE_APP_OPTIONS = 'SAVE_APP_OPTIONS';
export const DATA_WEDGE_STATE = 'DATA_WEDGE_STATE';

export const SET_ORGANIZATION = 'SET_ORGANIZATION'
export const SET_ENTERPRISE_UNIT = 'SET_ENTERPRISE_UNIT'
export const SET_ENVIRONMENT = 'SET_ENVIRONMENT'

export const ITEM_ATTRIBUTES_START = 'ITEM_ATTRIBUTES_START'
export const ITEM_ATTRIBUTES_SUCCESS = 'ITEM_ATTRIBUTES_SUCCESS'
export const ITEM_ATTRIBUTES_ERROR = 'ITEM_ATTRIBUTES_ERROR'

export const ITEM_PRICES_START = 'ITEM_PRICE_START'
export const ITEM_PRICES_SUCCESS = 'ITEM_PRICE_SUCCESS'
export const ITEM_PRICES_ERROR = 'ITEM_PRICE_ERROR'

export const OVERRIDE_ITEM_PRICES_START = 'OVERRIDE_ITEM_PRICES_START'
export const OVERRIDE_ITEM_PRICES_SUCCESS = 'OVERRIDE_ITEM_PRICES_SUCCESS'
export const OVERRIDE_ITEM_PRICES_ERROR = 'OVERRIDE_ITEM_PRICES_ERROR'

export const CREATE_NEW_ITEM_START = 'CREATE_NEW_ITEM_START'
export const CREATE_NEW_ITEM_SUCCESS = 'CREATE_NEW_ITEM_SUCCESS'
export const CREATE_NEW_ITEM_ERROR = 'CREATE_NEW_ITEM_ERROR'

export const EDIT_ITEM_ATTRIBUTES_START = 'EDIT_ITEM_ATTRIBUTES_START'
export const EDIT_ITEM_ATTRIBUTES_SUCCESS = 'EDIT_ITEM_ATTRIBUTES_SUCCESS'
export const EDIT_ITEM_ATTRIBUTES_ERROR = 'EDIT_ITEM_ATTRIBUTES_ERROR'

export const INVENTORY_CREATE_DOCUMENT_START = 'INVENTORY_CREATE_DOCUMENT_START'
export const INVENTORY_CREATE_DOCUMENT_SUCCESS = 'INVENTORY_CREATE_DOCUMENT_SUCCESS'
export const INVENTORY_CREATE_DOCUMENT_ERROR = 'INVENTORY_CREATE_DOCUMENT_ERROR'

export const GET_DEPARTMENTS_START = 'GET_DEPARTMENTS_START'
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_SUB_CATEGORIES_SUCCESS = 'GET_SUB_CATEGORIES_SUCCESS'
export const GET_DEPARTMENTS_ERROR = 'GET_DEPARTMENTS_ERROR'

export const DETECT_CHANGE = 'DETECT_CHANGE'

export enum STATUS_ENUM {
    INACTIVE = 'INACTIVE',
    ACTIVE = 'ACTIVE',
    DISCONTINUED = 'DISCONTINUED',
    SEASONAL = 'SEASONAL',
    TO_DISCONTINUE = 'TO_DISCONTINUE',
    UNAUTHORIZED = 'UNAUTHORIZED'
}